spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /db-console

  jpa:
    properties:
      generation-ddl: true
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: UTC
    show_sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

    open-in-view: false
  sql:
    init:
      platform: h2
      mode: always






